### ISSUE TITLE
how to use the E.T.Chat on my own dataset?

### ISSUE THREAD

**Issue by onlyonewater** [PolyU-ChenLab/ETBench#2]
Hi, authors, thanks for releasing this great work, now I want to use the E.T.Chat to infer my own dataset, could you give a demo or a tutorial about it? Thanks!!!

**Comment by yeliudev** [comment]
Thanks for your interest in our work! You may refer to the inference code [here](https://github.com/PolyU-ChenLab/ETBench/blob/main/etchat/eval/infer_etbench.py) for how to run the model on a specific dataset. Using this script, organizing your dataset annotations (`.jsonl` format) into the following format should work.

```
{"task": "task name", "video": "path to video 1", "q": "model input prompt 1"}
{"task": "task name", "video": "path to video 2", "q": "model input prompt 2"}
{"task": "task name", "video": "path to video 3", "q": "model input prompt 3"}
...
```

The model outputs would be saved in an additional `a` entry.

```
{"task": "task name", "video": "path to video 1", "q": "model input prompt 1", "a": "model output 1"}
{"task": "task name", "video": "path to video 2", "q": "model input prompt 2", "a": "model output 2"}
{"task": "task name", "video": "path to video 3", "q": "model input prompt 3", "a": "model output 3"}
...
```

**Comment by onlyonewater** [comment]
ok, got it, I will have a try, thanks!

**Comment by onlyonewater** [comment]
I saw that in the inference code, you get the 'src' from the annotations file, but in my custom data, the 'src' is None. I am not sure that my understanding is correct. and I do not know if it would affect the model's performance.

![image](https://github.com/user-attachments/assets/7434e21b-8c9d-4bf6-b611-d54540b50128)

**Comment by yeliudev** [comment]
This entry is for the case when your input prompt has timestamps, e.g., "What's happening at 23 seconds?". In this case, you may replace the timestamp with `<vid>` and put the timestamp (in seconds) into `src`. For example:

```
{"task": "task name", "video": "path to video", "q": "What's happening at <vid>?", "src": [23]}
```

If the prompt doesn't contain timestamps, simply setting `src` as `None` should be fine.

**Comment by onlyonewater** [comment]
Ok, got it, thanks!!
